---
apiVersion: v2
name: alfresco-common
description: |
  A helper subchart to avoid duplication in alfresco charts and set common
  external dependencies
type: library
version: 0.2.0
dependencies:
  - name: common
    repository: >-
      https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/
    version: 1.x.x
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
