apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alfresco-elasticsearch-connector.fullName" . }}-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: search
data:
  ELASTICSEARCH_INDEXNAME: "{{ .Values.indexName }}"
  SPRING_ELASTICSEARCH_REST_URIS: http://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}
  SPRING_ACTIVEMQ_BROKERURL: nio://{{ .Release.Name }}-activemq-broker:61616
  ALFRESCO_SHAREDFILESTORE_BASEURL: http://{{ template "alfresco.shortname" . }}-filestore:80/alfresco/api/-default-/private/sfs/versions/1/file/
  ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://{{ template "content-services.shortname" . }}-transform-misc/transform/config
  ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_REFRESHTIME: "{{ .Values.contentMediaTypeCache.refreshTime }}"
  ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_ENABLED: "{{ .Values.contentMediaTypeCache.enabled }}"
  ALFRESCO_PATHINDEXINGCOMPONENT.ENABLED: "{{ .Values.pathIndexingComponent.enabled }}"
  {{- if .Values.liveIndexing.environment }}
  {{- range $key, $val := .Values.liveIndexing.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
