{{- if .Values.reindexing.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "alfresco-elasticsearch-connector.fullName" . }}-reindexing
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alfresco-elasticsearch-connector.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "component-pod-security-context" .Values | indent 4 }}
      {{- include "alfresco-content-services.imagePullSecrets" . | indent 6 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-reindexing
          image: "{{ .Values.reindexing.image.repository }}:{{ .Values.reindexing.image.tag }}"
          imagePullPolicy: {{ .Values.reindexing.image.pullPolicy }}
          {{- include "component-security-context" .Values | indent 8 }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
          envFrom:
            - configMapRef:
                name: {{ template "alfresco-elasticsearch-connector.fullName" . }}-reindexing-configmap
            - secretRef:
                name: {{ default (printf "%s-brokersecret" (include "content-services.shortname" .)) .Values.messageBroker.existingSecretName }}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-dbsecret" (include "content-services.shortname" $)) $.Values.reindexing.postgresql.existingSecretName }}
                  key: DATABASE_PASSWORD
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-dbsecret" (include "content-services.shortname" $)) $.Values.reindexing.postgresql.existingSecretName }}
                  key: DATABASE_USERNAME
            {{- include "spring.activemq.env" . | nindent 12 }}
            {{- include "spring.elasticsearch.env.credentials" $ | nindent 12 }}
          ports:
              - name: http
                containerPort: 8080
                protocol: TCP
      initContainers:
        - name: wait-for-repository
          image: curlimages/curl:7.79.1
          {{- include "component-security-context" .Values | indent 8 }}
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
          env:
            - name: ALFRESCO_REPOSITORY_URL
              value: http://{{ template "content-services.shortname" . }}-repository/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-
          command: [ "/bin/sh","-c" ]
          # Delay running the reindexing to give Alfresco Repository a chance to fully initialise
          args: [ "while [ $(curl -sw '%{http_code}' $ALFRESCO_REPOSITORY_URL -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the Alfresco Repository...'; done; echo 'Alfresco is ready, delay reindexing to give a chance to fully initialise.'; sleep 30; echo 'Reindexing started!'" ]
{{ end }}
