title: ACS Deployment Documentation
description: User documentation for deploying Alfresco Content Services
theme: just-the-docs
color_scheme: alfresco

url: https://alfresco.github.io

aux_links:
  Hyland Support: https://support.hyland.com/p/alfresco
  Docs: https://docs.alfresco.com/
  GitHub Repository: https://github.com/Alfresco/acs-deployment

aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Improve this page on GitHub"
gh_edit_repository: https://github.com/Alfresco/acs-deployment
gh_edit_branch: master
gh_edit_source: .
gh_edit_view_mode: edit

logo: "/docs/images/hyland-alfresco-logos.png"
favicon_ico: "/docs/images/favicon.ico"

defaults:
  # apply the default layout to all markdown pages
  - scope:
      path: "*"
    values:
      layout: default
      render_with_liquid: false

exclude:
  - Brewfile
  - '*/ci/*'
  - Gemfile
  - Gemfile.lock
  - '*.yaml'
  - '*/Chart.lock'
  - '*.tgz'
  - '*/NOTES.txt'
  - README.md
  - LICENSE

plugins:
  - jekyll-relative-links

mermaid:
  version: "10.9.0"
