# This values file can be used to install ACS 7.4.x using the latest version of
# the chart
alfresco-repository:
  image:
    tag: 23.5.0
activemq:
  image:
    tag: 5.18.7-jre17-rockylinux8
alfresco-transform-service:
  transformrouter:
    image:
      tag: 4.1.7
  pdfrenderer:
    image:
      tag: 5.1.7
  imagemagick:
    image:
      tag: 5.1.7
  libreoffice:
    image:
      tag: 5.1.7
  tika:
    image:
      tag: 5.1.7
  transformmisc:
    image:
      tag: 5.1.7
  filestore:
    image:
      tag: 4.1.7
alfresco-ai-transformer:
  image:
    tag: 3.1.9
share:
  image:
    tag: 23.5.0
alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        tag: 5.1.0
    content:
      image:
        tag: 5.1.0
    metadata:
      image:
        tag: 5.1.0
    path:
      image:
        tag: 5.1.0
  reindexing:
    image:
      tag: 5.1.0
alfresco-search:
  enabled: false
  searchServicesImage:
    tag: 2.0.15
  insightEngineImage:
    tag: 2.0.15
alfresco-digital-workspace:
  image:
    tag: 5.3.0
alfresco-control-center:
  image:
    tag: 9.3.0
postgresql:
  image:
    tag: 15.10.0
postgresql-sync:
  image:
    tag: 14.10.0
alfresco-sync-service:
  image:
    tag: 5.1.0
alfresco-connector-ms365:
  image:
    tag: 2.0.6
alfresco-connector-msteams:
  image:
    tag: 2.0.6
alfresco-audit-storage:
  image:
    tag: 1.1.0
dtas:
  config:
    assertions:
      acs:
        version: 23.5.0
        modules:
        - id: org_alfresco_device_sync_repo
          version: 5.1.0
          installed: true
        - id: org.alfresco.integrations.google.docs
          version: 4.1.0
          installed: true
        - id: alfresco-aos-module
          version: 3.3.0
          installed: true
