# This values file can be used to install ACS 7.4.x using the latest version of
# the chart
alfresco-repository:
  image:
    tag: 23.6.1
activemq:
  image:
    tag: 5.19.2-jre17-rockylinux8
alfresco-transform-service:
  transformrouter:
    image:
      tag: 4.3.2-A.2
  pdfrenderer:
    image:
      tag: 5.3.2-A.2
  imagemagick:
    image:
      tag: 5.3.2-A.2
  libreoffice:
    image:
      tag: 5.3.2-A.2
  tika:
    image:
      tag: 5.3.2-A.2
  transformmisc:
    image:
      tag: 5.3.2-A.2
  filestore:
    image:
      tag: 4.3.2-A.2
alfresco-ai-transformer:
  image:
    tag: 3.3.2-A.2
share:
  image:
    tag: 23.6.1
alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        tag: 5.4.0-A.2
    content:
      image:
        tag: 5.4.0-A.2
    metadata:
      image:
        tag: 5.4.0-A.2
    path:
      image:
        tag: 5.4.0-A.2
  reindexing:
    image:
      tag: 5.4.0-A.2
alfresco-search:
  enabled: false
  searchServicesImage:
    tag: 2.0.18-SNAPSHOT
  insightEngineImage:
    tag: 2.0.18-SNAPSHOT
alfresco-digital-workspace:
  image:
    tag: 7.2.0
alfresco-control-center:
  image:
    tag: 10.2.0
postgresql:
  image:
    tag: 15.10
postgresql-sync:
  image:
    tag: 15.10
alfresco-sync-service:
  image:
    tag: 5.3.0
alfresco-connector-ms365:
  image:
    tag: 2.1.0-A.2
alfresco-connector-msteams:
  image:
    tag: 2.1.0-A.4
alfresco-audit-storage:
  image:
    tag: 1.3.0-A.3
dtas:
  config:
    assertions:
      acs:
        version: 23.6.1
        modules:
        - id: org_alfresco_device_sync_repo
          version: 5.3.0
          installed: true
        - id: org.alfresco.integrations.google.docs
          version: 4.1.0
          installed: true
        - id: alfresco-aos-module
          version: 3.4.0
          installed: true
