# This is a YAML-formatted file.  Declare variables to be passed into your templates.

repository:
  image:
    tag: 7.1.1-A5

transformrouter:
  image:
    tag: 1.5.1

pdfrenderer:
  image:
    tag: 2.5.6

imagemagick:
  image:
    tag: 2.5.6

libreoffice:
  image:
    tag: 2.5.6

tika:
  image:
    tag: 2.5.6

transformmisc:
  image:
    tag: 2.5.6

aiTransformer:
  image:
    tag: 1.4.0

filestore:
  image:
    tag: 0.16.1-A1

share:
  image:
    tag: 7.1.1-A5

alfresco-search:
  searchServicesImage:
    tag: 2.0.2

alfresco-sync-service:
  syncservice:
    image:
      tag: 3.4.0
