# This values file can be used to install ACS 7.1.x using the latest version of
# the chart
alfresco-repository:
  image:
    tag: 7.1.1.9
  configuration:
    search:
      flavor: solr6
activemq:
  image:
    repository: quay.io/alfresco/alfresco-activemq
    tag: 5.16.7-jre17-rockylinux8
alfresco-ai-transformer:
  image:
    tag: 1.5.1
alfresco-transform-service:
  transformrouter:
    image:
      tag: 2.1.2
  pdfrenderer:
    image:
      tag: 3.1.2
  imagemagick:
    image:
      tag: 3.1.2
  libreoffice:
    image:
      tag: 3.1.2
  tika:
    image:
      tag: 3.1.2
  transformmisc:
    image:
      tag: 3.1.2
  filestore:
    image:
      tag: 2.1.2
share:
  image:
    tag: 7.1.1.9
alfresco-search:
  enabled: true
  repository:
    securecomms: none
  searchServicesImage:
    tag: 2.0.2.2
  insightEngineImage:
    tag: 2.0.2.2
alfresco-search-enterprise:
  enabled: false
  liveIndexing:
    mediation:
      image:
        tag: 3.1.1.1
    content:
      image:
        tag: 3.1.1.1
    metadata:
      image:
        tag: 3.1.1.1
    path:
      image:
        tag: 3.1.1.1
  reindexing:
    image:
      tag: 3.1.1.1
elasticsearch:
  enabled: false
postgresql:
  image:
    tag: 13.3.0
postgresql-sync:
  image:
    tag: 13.3.0
alfresco-digital-workspace:
  image:
    tag: 4.4.1
alfresco-sync-service:
  image:
    tag: 3.11.3
alfresco-connector-msteams:
  image:
    tag: 1.1.0
alfresco-connector-ms365:
  image:
    tag: 1.1.1
alfresco-control-center:
  enabled: false
global:
  search:
    securecomms: none
dtas:
  config:
    assertions:
      acs:
        version: 7.1.1
        modules:
        - id: org.alfresco.integrations.google.docs
          version: 3.2.1.3
          installed: true
        - id: alfresco-aos-module
          version: 1.4.0.1
          installed: true
