repository:
  image:
    repository: quay.io/alfresco/alfresco-content-repository-aws
    tag: "6.1.1-RC3"

share:
  image:
    repository: quay.io/alfresco/alfresco-share-aws
    tag: "6.1.1-RC2"

ai:
  enabled: true

s3connector:
  enabled: true
