repository:
  image:
    repository: quay.io/alfresco/alfresco-content-repository-aws
    tag: "6.2.0.1"

share:
  image:
    repository: quay.io/alfresco/alfresco-share-aws
    tag: "6.2.0"

ai:
  enabled: true

s3connector:
  enabled: true
