repository:
  image:
    repository: quay.io/alfresco/alfresco-content-repository-aws
    tag: "6.2.0-RC3"

share:
  image:
    repository: quay.io/alfresco/alfresco-share-aws
    tag: "6.2.0-RC4"

ai:
  enabled: true

s3connector:
  enabled: true
