repository:
  image:
    repository: quay.io/alfresco/alfresco-content-repository-aws
    tag: "6.2.2-RC1"

share:
  image:
    repository: quay.io/alfresco/alfresco-share-aws
    tag: "6.2.2-RC3"

ai:
  enabled: true

s3connector:
  enabled: true
