repository:
  image:
    repository: quay.io/alfresco/alfresco-content-repository-aws
    tag: "latest"

share:
  image:
    repository: quay.io/alfresco/alfresco-share-aws
    tag: "6.1.0.2"

ai:
  enabled: true

s3connector:
  enabled: true
