# This values file can be used to install ACS with pre released images using the latest version of
# the chart
alfresco-repository:
  image:
    tag: 26.1.0-A.17
activemq:
  image:
    repository: quay.io/alfresco/alfresco-activemq
    tag: 6.2.1-jre17-rockylinux8
alfresco-transform-service:
  transformrouter:
    image:
      tag: 4.3.2-A.2
  pdfrenderer:
    image:
      tag: 5.3.2-A.2
  imagemagick:
    image:
      tag: 5.3.2-A.2
  libreoffice:
    image:
      tag: 5.3.2-A.2
  tika:
    image:
      tag: 5.3.2-A.2
  transformmisc:
    image:
      tag: 5.3.2-A.2
  filestore:
    image:
      tag: 4.3.2-A.2
alfresco-ai-transformer:
  image:
    tag: 3.3.2-A.2
share:
  image:
    tag: 26.1.0-A.17
alfresco-search:
  searchServicesImage:
    tag: 2.1.0-A9
  insightEngineImage:
    tag: 2.1.0-A9
alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        tag: 5.4.0-A.2
    content:
      image:
        tag: 5.4.0-A.2
    metadata:
      image:
        tag: 5.4.0-A.2
    path:
      image:
        tag: 5.4.0-A.2
  reindexing:
    image:
      tag: 5.4.0-A.2
alfresco-digital-workspace:
  image:
    tag: 7.3.0-22434626274
alfresco-control-center:
  image:
    tag: 10.3.0-22434626274
postgresql:
  image:
    tag: 16.5
postgresql-sync:
  image:
    tag: 16.5
alfresco-sync-service:
  image:
    tag: 5.3.0
alfresco-connector-ms365:
  image:
    tag: 2.1.0-A.2
alfresco-connector-msteams:
  image:
    tag: 2.1.0-A.4
elasticsearch:
  elasticsearch:
    image:
      tag: 8.17.3
  kibana:
    image:
      tag: 8.17.1
alfresco-audit-storage:
  image:
    tag: 1.3.0-A.3
dtas:
  config:
    assertions:
      acs:
        version: 26.1.0
        modules:
        - id: org_alfresco_device_sync_repo
          version: 5.3.0
          installed: true
        - id: org.alfresco.integrations.google.docs
          version: 4.1.0
          installed: true
        - id: alfresco-aos-module
          version: 3.4.1-A.1
          installed: true
