# This values file can be used to install ACS with pre released images using the latest version of
# the chart
alfresco-repository:
  image:
    tag: 25.1.0-A.3
activemq:
  image:
    repository: quay.io/alfresco/alfresco-activemq
    tag: 5.18.6-jre17-rockylinux8
alfresco-transform-service:
  transformrouter:
    image:
      tag: 4.1.5
  pdfrenderer:
    image:
      tag: 5.1.5
  imagemagick:
    image:
      tag: 5.1.5
  libreoffice:
    image:
      tag: 5.1.5
  tika:
    image:
      tag: 5.1.5
  transformmisc:
    image:
      tag: 5.1.5
  filestore:
    image:
      tag: 4.1.5
alfresco-ai-transformer:
  image:
    tag: 3.1.7
share:
  image:
    tag: 25.1.0-A.3
alfresco-search:
  searchServicesImage:
    tag: 2.1.0-A9
  insightEngineImage:
    tag: 2.1.0-A9
alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        tag: 4.3.0-A.1
    content:
      image:
        tag: 4.3.0-A.1
    metadata:
      image:
        tag: 4.3.0-A.1
    path:
      image:
        tag: 4.3.0-A.1
  reindexing:
    image:
      tag: 4.3.0-A.1
alfresco-digital-workspace:
  image:
    tag: 5.3.0-12312682746
alfresco-control-center:
  image:
    tag: 9.3.0-12312682746
postgresql:
  image:
    tag: 14.4.0
postgresql-syncservice:
  image:
    tag: 14.4.0
alfresco-sync-service:
  image:
    tag: 5.2.0-A1
alfresco-connector-ms365:
  image:
    tag: 2.0.4-A4
alfresco-connector-msteams:
  image:
    tag: 2.0.4-A4
alfresco-audit-storage:
  image:
    tag: 1.0.0
elasticsearch:
  imageTag: 8.5.1
kibana-audit:
  imageTag: 8.5.1
elasticsearch-audit:
  imageTag: 8.5.1
dtas:
  config:
    assertions:
      acs:
        version: 25.1.0
        modules:
        - id: org.alfresco.integrations.google.docs
          version: 4.1.0
          installed: true
