# This values file can be used to install ACS with pre released images using the latest version of
# the chart
alfresco-repository:
  image:
    tag: 25.2.0-A.13
activemq:
  image:
    repository: quay.io/alfresco/alfresco-activemq
    tag: 5.18.7-jre17-rockylinux8
alfresco-transform-service:
  transformrouter:
    image:
      tag: 4.1.7
  pdfrenderer:
    image:
      tag: 5.1.7
  imagemagick:
    image:
      tag: 5.1.7
  libreoffice:
    image:
      tag: 5.1.7
  tika:
    image:
      tag: 5.1.7
  transformmisc:
    image:
      tag: 5.1.7
  filestore:
    image:
      tag: 4.1.7
alfresco-ai-transformer:
  image:
    tag: 3.1.9
share:
  image:
    tag: 25.2.0-A.13
alfresco-search:
  searchServicesImage:
    tag: 2.1.0-A9
  insightEngineImage:
    tag: 2.1.0-A9
alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        tag: 5.1.0
    content:
      image:
        tag: 5.1.0
    metadata:
      image:
        tag: 5.1.0
    path:
      image:
        tag: 5.1.0
  reindexing:
    image:
      tag: 5.1.0
alfresco-digital-workspace:
  image:
    tag: 7.0.0-15484965223
alfresco-control-center:
  image:
    tag: 10.0.0-15484965223
postgresql:
  image:
    tag: 16.5.0
postgresql-sync:
  image:
    tag: 16.5.0
alfresco-sync-service:
  image:
    tag: 5.2.0-A8
alfresco-connector-ms365:
  image:
    tag: 2.0.6-A.2
alfresco-connector-msteams:
  image:
    tag: 2.0.6-A.2
elastisearch:
  image:
    tag: 8.17.3
  kibana:
    image:
      tag: 8.17.1
alfresco-audit-storage:
  image:
    tag: 1.1.1-A.2
dtas:
  config:
    assertions:
      acs:
        version: 25.2.0
        modules:
        - id: org.alfresco.integrations.google.docs
          version: 4.1.0
          installed: true
