# Defines the list of dependent charts required by this chart
# Alfresco Content Services product requires
# - a postgres DB
# - the alfresco-infrastructure chart; Details here: https://github.com/Alfresco/alfresco-infrastructure-deployment
#       currently only the pvc (https://github.com/Alfresco/alfresco-infrastructure-deployment/blob/master/charts/incubator/alfresco-infrastructure/templates/pvc.yaml)
#       is really required from the alfresco-infrastructure to start up the Alfresco Content Services product
dependencies:
- name: postgresql
  version: 0.9.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: alfresco-search
  version: 0.0.8
  repository: https://kubernetes-charts.alfresco.com/stable
  condition: alfresco-search.enabled
- name: alfresco-infrastructure
  version: 2.0.0
  condition: alfresco-content-services.alfresco-infrastructure.enabled
  repository: https://kubernetes-charts.alfresco.com/stable
- name: alfresco-digital-workspace
  version: 1.0.0
  condition: alfresco-digital-workspace.enabled
  repository: https://kubernetes-charts.alfresco.com/stable
