
dependencies:
- name: postgresql
  version: 0.9.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: alfresco-infrastructure
  version: 0.1.0-DEPLOY-426
  condition: alfresco-content-services.alfresco-infrastructure.enabled
  repository: http://kubernetes-charts.alfresco.com/incubator