dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: postgresql
  version: 8.6.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: postgresql-syncservice
  condition: postgres-syncservice.enabled
- name: alfresco-adf-app
  alias: alfresco-digital-workspace
  version: 2.2.0
  repository: https://kubernetes-charts.alfresco.com/stable
  condition: alfresco-content-services.alfresco-digital-workspace.enabled,alfresco-digital-workspace.enabled
