dependencies:
  - name: postgresql
    version: 8.9.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: postgresql
    version: 8.9.6
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql-syncservice
    condition: alfresco-sync-service.syncservice.enabled,postgresql-syncservice.enabled
  - name: common
    alias: alfresco-digital-workspace
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M12
    condition: alfresco-content-services.alfresco-digital-workspace.enabled,alfresco-digital-workspace.enabled
  - name: activemq
    version: 2.0.0
  - name: alfresco-search
    version: 1.0.4
  - name: alfresco-sync-service
    version: 3.0.9
