# Defines the properties required by the imagemagick container
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.shortname" . }}-imagemagick-configmap
  labels:
    {{- include "imagemagick.labels" . | nindent 4 }}
data:
  # The JAVA_OPTS defined in the values.yaml file for the "imagemagick" are set here using proper quotes
  {{- if .Values.imagemagick.environment }}
  {{- range $key, $val := .Values.imagemagick.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{- include "activemq.config" . | nindent 2 }}
  FILE_STORE_URL: http://{{ template "alfresco.shortname" . }}-filestore:80/alfresco/api/-default-/private/sfs/versions/1/file
  livenessPercent: "{{ .Values.imagemagick.livenessProbe.livenessPercent }}"
  livenessTransformPeriodSeconds: "{{ .Values.imagemagick.livenessProbe.livenessTransformPeriodSeconds }}"
  maxTransforms: "{{ .Values.imagemagick.livenessProbe.maxTransforms }}"
  maxTransformSeconds: "{{ .Values.imagemagick.livenessProbe.maxTransformSeconds }}"
