# Defines the properties required by the alfresco-pdf-renderer container
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.fullname" . }}-alfrescopdfrenderer-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: transformers
data:
  # The JAVA_OPTS defined in the values.yaml file for the "alfrescopdfrenderer" are set here using proper quotes
  {{- if .Values.alfrescopdfrenderer.environment }}
  {{- range $key, $val := .Values.alfrescopdfrenderer.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  livenessPercent: "{{ .Values.alfrescopdfrenderer.livenessProbe.livenessPercent }}"
  livenessTransformPeriodSeconds: "{{ .Values.alfrescopdfrenderer.livenessProbe.livenessTransformPeriodSeconds }}"
  maxTransforms: "{{ .Values.alfrescopdfrenderer.livenessProbe.maxTransforms }}"
  maxTransformSeconds: "{{ .Values.alfrescopdfrenderer.livenessProbe.maxTransformSeconds }}"