# Defines the properties required by the alfresco-tika container
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.shortname" . }}-tika-configmap
  labels:
    {{- include "tika.labels" . | nindent 4 }}
data:
  # The JAVA_OPTS defined in the values.yaml file for "tika" are set here using proper quotes
  {{- if .Values.tika.environment }}
  {{- range $key, $val := .Values.tika.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{ template "activemq.config" . }}
  FILE_STORE_URL: http://{{ template "alfresco.shortname" . }}-filestore:80/alfresco/api/-default-/private/sfs/versions/1/file
  livenessPercent: "{{ .Values.tika.livenessProbe.livenessPercent }}"
  livenessTransformPeriodSeconds: "{{ .Values.tika.livenessProbe.livenessTransformPeriodSeconds }}"
  maxTransforms: "{{ .Values.tika.livenessProbe.maxTransforms }}"
  maxTransformSeconds: "{{ .Values.tika.livenessProbe.maxTransformSeconds }}"
