# Defines the properties required by the transform router container
{{- if eq .Values.repository.edition "Enterprise" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alfresco.shortname" . }}-router-configmap
  labels:
    {{- include "transform-router.labels" . | nindent 4 }}
data:
  # The JAVA_OPTS defined in the values.yaml file for "transformrouter" are set here using proper quotes
  {{- if .Values.transformrouter.environment }}
  {{- range $key, $val := .Values.transformrouter.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{- include "activemq.config" . | nindent 2 }}
  IMAGEMAGICK_URL: http://{{ template "content-services.shortname" . }}-imagemagick:80
  PDF_RENDERER_URL: http://{{ template "content-services.shortname" . }}-pdfrenderer:80
  LIBREOFFICE_URL: http://{{ template "content-services.shortname" . }}-libreoffice:80
  TIKA_URL: http://{{ template "content-services.shortname" . }}-tika:80
  {{- if .Values.transformmisc.enabled }}
  MISC_URL: http://{{ template "content-services.shortname" . }}-transform-misc:80
  {{- end }}
  FILE_STORE_URL: http://{{ template "alfresco.shortname" . }}-filestore:80/alfresco/api/-default-/private/sfs/versions/1/file
  {{- if .Values.global.ai.enabled }}
  TRANSFORMER_URL_AWS_AI: http://{{ template "content-services.shortname" . }}-ai-transformer:80
  TRANSFORMER_QUEUE_AWS_AI: "org.alfresco.transform.engine.ai-aws.acs"
  TRANSFORMER_ROUTES_ADDITIONAL_AI: "/mnt/routes/ai-pipeline-routes.json"

    {{- end }}
{{- end }}
