{{- if .Values.global.ai.enabled }}
# Defines the properties required by the alfresco-ai-transformer container
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.shortname" . }}-ai-transformer-configmap
  labels:
    {{- include "ai-transformer.labels" . | nindent 4 }}
data:
  # The JAVA_OPTS defined in the values.yaml file for "ai" are set here using proper quotes
  {{- if .Values.aiTransformer.environment }}
  {{- range $key, $val := .Values.aiTransformer.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{ template "activemq.config" . }}
  FILE_STORE_URL: http://{{ template "alfresco.shortname" . }}-filestore:80/alfresco/api/-default-/private/sfs/versions/1/file
  AWS_ACCESS_KEY: {{ .Values.ai.aws.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ai.aws.secretAccessKey }}
  AWS_REGION: {{ .Values.ai.aws.region }}
  AWS_S3_BUCKET: {{ .Values.ai.aws.s3Bucket }}
  AWS_COMPREHEND_ROLE_ARN: {{ .Values.ai.aws.comprehendRoleARN }}
  livenessPercent: "{{ .Values.aiTransformer.livenessProbe.livenessPercent }}"
  livenessTransformPeriodSeconds: "{{ .Values.aiTransformer.livenessProbe.livenessTransformPeriodSeconds }}"
  maxTransforms: "{{ .Values.aiTransformer.livenessProbe.maxTransforms }}"
  maxTransformSeconds: "{{ .Values.aiTransformer.livenessProbe.maxTransformSeconds }}"
{{- end }}
