{{- if .Values.transformmisc.enabled }}
# Defines the properties required by the alfresco-transform-misc container
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.shortname" . }}-transform-misc-configmap
  labels:
    {{- include "transform-misc.labels" . | nindent 4 }}
data:
  # The JAVA_OPTS defined in the values.yaml file for "transform-misc" are set here using proper quotes
  {{- if .Values.transformmisc.environment }}
  {{- range $key, $val := .Values.transformmisc.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{- include "activemq.config" . | nindent 2 }}
  FILE_STORE_URL: http://{{ template "alfresco.shortname" . }}-filestore:80/alfresco/api/-default-/private/sfs/versions/1/file
  livenessPercent: "{{ .Values.transformmisc.livenessProbe.livenessPercent }}"
  livenessTransformPeriodSeconds: "{{ .Values.transformmisc.livenessProbe.livenessTransformPeriodSeconds }}"
  maxTransforms: "{{ .Values.transformmisc.livenessProbe.maxTransforms }}"
  maxTransformSeconds: "{{ .Values.transformmisc.livenessProbe.maxTransformSeconds }}"
{{- end }}
