{{- if eq .Values.repository.edition "Enterprise" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "alfresco.shortname" . }}-router
  labels:
    {{- include "transform-router.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.transformrouter.replicaCount }}
  selector:
    matchLabels:
      {{- include "transform-router.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
{{ toYaml .Values.global.strategy.rollingUpdate | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-transform-router.yaml") . | sha256sum }}
        checksum/config-routes: {{ include (print $.Template.BasePath "/config-transformer-routes.yaml") . | sha256sum }}
      labels:
        {{- include "transform-router.selectorLabels" . | nindent 8 }}
    spec:
    {{- include "component-pod-security-context" .Values.transformrouter | indent 4 }}
    {{- if .Values.transformrouter.nodeSelector }}
      nodeSelector: {{- .Values.transformrouter.nodeSelector | toYaml | nindent 8 }}
    {{- end }}
      {{- include "alfresco-content-services.imagePullSecrets" . | indent 6 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "alfresco.shortname" . }}-router
              topologyKey: failure-domain.beta.kubernetes.io/zone
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "alfresco.shortname" . }}-router
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.transformrouter.image.repository }}:{{ .Values.transformrouter.image.tag }}"
          imagePullPolicy: {{ .Values.transformrouter.image.pullPolicy }}
          {{- include "component-security-context" .Values.transformrouter | indent 8 }}
          envFrom:
          - configMapRef:
              # config map to use, defined in config-transform-router.yaml
              name: {{ template "alfresco.shortname" . }}-router-configmap
          - secretRef:
              name: {{ default (printf "%s-brokersecret" (include "content-services.shortname" .)) .Values.messageBroker.existingSecretName }}
          env:
            {{- include "activemq.env" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.transformrouter.image.internalPort }}
          resources:
{{ toYaml .Values.transformrouter.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.transformrouter.image.internalPort }}
            initialDelaySeconds: {{ .Values.transformrouter.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.transformrouter.livenessProbe.periodSeconds }}
            failureThreshold: 1
            timeoutSeconds: {{ .Values.transformrouter.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.transformrouter.image.internalPort }}
            initialDelaySeconds: {{ .Values.transformrouter.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.transformrouter.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.transformrouter.readinessProbe.timeoutSeconds }}
          {{- if .Values.global.ai.enabled }}
          volumeMounts:
          - name: config-volume
            mountPath: /mnt/routes
          {{- end }}
      {{- if .Values.global.ai.enabled }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "alfresco.shortname" . }}-transform-routes-configmap
      {{- end }}
{{- end }}
