# Defines the deployment for the pdfrenderer transformer app
# Details: https://git.alfresco.com/Repository/alfresco-docker-transformers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "content-services.shortname" . }}-pdfrenderer
  labels:
    {{- include "pdfrenderer.labels" . | nindent 6 }}
spec:
  replicas: {{ .Values.pdfrenderer.replicaCount }}
  selector:
    matchLabels:
      {{- include "pdfrenderer.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
{{ toYaml .Values.global.strategy.rollingUpdate | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-pdfrenderer.yaml") . | sha256sum }}
      labels:
        {{- include "pdfrenderer.selectorLabels" . | nindent 8 }}
    spec:
    {{- include "component-pod-security-context" .Values.pdfrenderer | indent 4 }}
    {{- if .Values.pdfrenderer.nodeSelector }}
      nodeSelector: {{- .Values.pdfrenderer.nodeSelector | toYaml | nindent 8 }}
    {{- end }}
      {{- include "alfresco-content-services.imagePullSecrets" . | indent 6 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "content-services.shortname" . }}-pdfrenderer
              topologyKey: failure-domain.beta.kubernetes.io/zone
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "content-services.shortname" . }}-pdfrenderer
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.pdfrenderer.image.repository }}:{{ .Values.pdfrenderer.image.tag }}"
          imagePullPolicy: {{ .Values.pdfrenderer.image.pullPolicy }}
          {{- include "component-security-context" .Values.pdfrenderer | indent 8 }}
          envFrom:
          - configMapRef:
              # config map to use, defined in config-pdfrenderer.yaml
              name: {{ template "content-services.shortname" . }}-pdfrenderer-configmap
          - secretRef:
              name: {{ default (printf "%s-brokersecret" (include "content-services.shortname" .)) .Values.messageBroker.existingSecretName }}
          env:
            {{- include "activemq.env" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.pdfrenderer.image.internalPort }}
          resources:
{{ toYaml .Values.pdfrenderer.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.pdfrenderer.image.internalPort }}
            initialDelaySeconds: {{ .Values.pdfrenderer.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.pdfrenderer.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.pdfrenderer.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.pdfrenderer.image.internalPort }}
            initialDelaySeconds: {{ .Values.pdfrenderer.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.pdfrenderer.livenessProbe.periodSeconds }}
            failureThreshold: 1
            timeoutSeconds: {{ .Values.pdfrenderer.livenessProbe.timeoutSeconds }}
