# Defines the deployment for the alfrescopdfrenderer transformer app
# Details: https://git.alfresco.com/Repository/alfresco-docker-transformers
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "content-services.fullname" . }}-alfrescopdfrenderer
  labels:
    app: {{ template "content-services.fullname" . }}-alfrescopdfrenderer
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.alfrescopdfrenderer.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "content-services.fullname" . }}-alfrescopdfrenderer
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.registryPullSecrets }}
      # only set this secret if a private docker registry variable is defined
      imagePullSecrets:
        - name: {{ .Values.registryPullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.alfrescopdfrenderer.image.repository }}:{{ .Values.alfrescopdfrenderer.image.tag }}"
          imagePullPolicy: {{ .Values.alfrescopdfrenderer.image.pullPolicy }}
          envFrom:
          - configMapRef:
              # config map to use, defined in config-alfrescopdfrenderer.yaml
              name: {{ template "content-services.fullname" . }}-alfrescopdfrenderer-configmap
          ports:
            - containerPort: {{ .Values.alfrescopdfrenderer.image.internalPort }}
          resources:
{{ toYaml .Values.alfrescopdfrenderer.resources | indent 12 }}
