apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "content-services.fullname" . }}-share
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"  
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.share.ingress.path }}
        backend:
          serviceName: {{ template "content-services.fullname" . }}-share
          servicePort: {{ .Values.share.service.externalPort }}