# Defines the ingress for the alfresco share app
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "content-services.shortname" . }}-share
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Default limit is 1m, document(s) above this size will throw 413 (Request Entity Too Large) error
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ ^(/.*/proxy/alfresco/api/solr/.*)$ {return 403 ;}
                  location ~ ^(/.*/-default-/proxy/alfresco/api/.*)$ {return 403;}
    
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.share.ingress.path }}
        backend:
          serviceName: {{ template "content-services.shortname" . }}-share
          servicePort: {{ .Values.share.service.externalPort }}
