{{- if .Values.network-policy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: search-allow-repository
spec:
  podSelector:
    matchLabels:
      app: {{ template "alfresco-search.host" . }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "content-services.fullname" . }}-repository
      ports:
        - protocol: TCP
          port: 8983
{{- end }}
