{{- if .Values.network-policy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-allow-repository
spec:
  podSelector:
    matchLabels:
      app: {{ template "database.hostname" . }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "content-services.fullname" . }}-repository
      ports:
        - protocol: TCP
          port: {{ template "database.port" . }}
{{- end }}
