{{- if .Values.networkpolicysetting.enabled }}
# Deny kubernetes dashboard
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-dashboard
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  policyTypes:
  - Ingress
  - Egress
{{- end }}