{{- if .Values.networkpolicysetting.enabled }}
{{- if index .Values "alfresco-search" "enabled" }}
# Allow search communication with other components
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: search
spec:
  podSelector:
    matchLabels:
      app: {{ template "alfresco-search.host" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      # Allow repository to access search
      - podSelector:
          matchLabels:
            app: {{ template "content-services.shortname" . }}-repository

      # Allow nginx-ingress to access search
      - podSelector:
          matchLabels:
            app: nginx-ingress

      # Allow Search to access itself
      - podSelector:
          matchLabels:
            app: {{ template "alfresco-search.host" . }}

      ports:
        - protocol: TCP
          port: 8983
  egress:
    # Allow search to communicate back with other components
    - to:
      # Repo
      - podSelector:
          matchLabels:
             app: {{ template "content-services.shortname" . }}-repository
      
      # nginx-ingress
      - podSelector:
          matchLabels:
             app: nginx-ingress

      # Allow Search to access itself
      - podSelector:
          matchLabels:
            app: {{ template "alfresco-search.host" . }}

    # Allow DB to communicate with EFS
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
      - protocol: TCP
        port: 2049
{{- end }}
{{- end }}