{{- if .Values.ai.enabled }}
# Defines the service for the ai transformer app
apiVersion: v1
kind: Service
metadata:
  name: {{ template "content-services.shortname" . }}-ai-transformer
  labels:
    {{- include "ai-transformer.selectorLabels" . | nindent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.aiTransformer.service.type }}
  ports:
  - port: {{ .Values.aiTransformer.service.externalPort }}
    targetPort: {{ .Values.aiTransformer.image.internalPort }}
    name: {{ .Values.aiTransformer.service.name }}
  selector:
    {{- include "ai-transformer.selectorLabels" . | nindent 4 }}
{{- end }}
