# Defines the service for the alfrescopdfrenderer transformer app
apiVersion: v1
kind: Service
metadata:
  name: {{ template "content-services.fullname" . }}-alfrescopdfrenderer
  labels:
    app: {{ template "content-services.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: transformers
spec:
  type: {{ .Values.alfrescopdfrenderer.service.type }}
  ports:
    - port: {{ .Values.alfrescopdfrenderer.service.externalPort }}
      targetPort: {{ .Values.alfrescopdfrenderer.image.internalPort }}
      name: {{ .Values.alfrescopdfrenderer.service.name }}
  selector:
    app: {{ template "content-services.fullname" . }}-alfrescopdfrenderer
    release: {{ .Release.Name }}