{{- if .Values.insightzeppelin.enabled }}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "alfresco-insight-zeppelin.fullName" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        {{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            Name: {{ template "alfresco-insight-zeppelin.fullName" . }}
            port:
              number: {{ .Values.service.externalPort }}
        {{- else }}
        backend:
          serviceName: {{ template "alfresco-insight-zeppelin.fullName" . }}
          servicePort: {{ .Values.service.externalPort }}
        {{- end }}
{{- end }}
