apiVersion: v2
description: A Helm chart for deploying Alfresco Insight Zeppelin
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
  - zeppelin
  - insight zeppelin
  - alfresco zeppelin
  - alfresco insight zeppelin
name: alfresco-insight-zeppelin
sources:
  - https://github.com/Alfresco/acs-deployment
version: 1.2.0-SNAPSHOT
appVersion: 2.0.6
dependencies:
  - name: alfresco-common
    version: 1.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
