{{- if and (not .Values.ingress.existingSecretName) .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr
  labels:
    app: {{ template "alfresco-search.fullName" . }}-solr
    release: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ .Values.ingress.basicAuth | quote }}
{{- end }}
