apiVersion: v2
description: A Helm chart for deploying Alfresco Search
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
  - search
  - search services
  - alfresco search services
  - insight
  - insight engine
  - alfresco insight engine
name: alfresco-search
sources:
  - https://github.com/alfresco/alfresco-search-deployment
version: 1.0.4
dependencies:
  - name: alfresco-insight-zeppelin
    version: 1.0.3
