---
apiVersion: v2
name: alfresco-elasticsearch-connector
description: A Helm chart for deploying Alfresco Elasticsearch connector
type: application
version: 0.1.0
appVersion: 3.0.0
dependencies:
  - name: alfresco-common
    version: 0.1.0-SNAPSHOT
    repository: https://kubernetes-charts.alfresco.com/incubator
