---
apiVersion: v2
description: Alfresco Sync Service
keywords:
  - syncservice
  - alfresco
  - application
name: alfresco-sync-service
sources:
  - https://github.com/Alfresco/acs-deployment
version: 3.2.0-SNAPSHOT
appVersion: 4.0.0-M6
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
dependencies:
  - name: common
    repository: >-
      https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/
    version: 1.x.x
  - name: alfresco-common
    version: 1.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
