apiVersion: v1
description: Alfresco Syncservice
keywords:
  - syncservice
  - alfresco
  - application
maintainers:
  - name: Alfresco Apps Repo Team
name: alfresco-sync-service
version: 3.0.9
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
